language: python
python:
  - "3.6"
# command to install dependencies
install: "pip install -r crawler/requirements.txt"
install: "pip install -r web/requirements.txt"
install: "pip install -r receiver/requirements.txt"

jobs:
  include:
  - stage: test
    name: "crawler tests"
    before_script: cd crawler
    script: python -m pytest
  - stage: test
    name: "web tests"
    before_script: cd web
    script: python -m pytest
  - stage: test
    name: "receiver tests"
    before_script: cd receiver
    script: python -m pytest
